modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "hexkeys"
version = "${version}"
displayName = "Hex Keys"
logoFile = "hexkeys.png"
authors = "MoonlitJolteon"
description = '''
Hex Keys: Accessing your inner thoughts
'''

[[dependencies.hexkeys]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexkeys]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexkeys]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexkeys]]
modId = "hexcasting"
mandatory = true
versionRange = "[0.11.3,)"
ordering = "NONE"
side = "BOTH"
